name: Build using Gradle

on: [ pull_request, push ]

jobs:
  Build:
    uses: JourneyHQ/Workflows/.github/workflows/gradle-build.yml@main
    with:
      emoji: 📘
      gradle_command: build
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}